[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf-voice-chatbot"
version = "1.0.0"
description = "Advanced Secure RAG Voice-enabled PDF Chatbot"
authors = [
    { name = "Chetan Nag" }
]
readme = "README.md"
requires-python = ">=3.10"
